#!/bin/sh
#--------------------------------------------------------
echo "==== Informasi detail IP ====" > ipinfo.txt
curl -s http://ip-api.com/json/\?fields=country,countryCode,region,regionName,city,timezone,isp,org,as,asname,query >> ipinfo.txt
sed -i 's/{"//g' ipinfo.txt
sed -i 's/","/\n/g' ipinfo.txt
sed -i 's/":"/ : /g' ipinfo.txt
sed -i 's/"}//g' ipinfo.txt
sed -i 's/":/ : /g' ipinfo.txt
sed -i 's/,"/\n/g' ipinfo.txt
sed -i 's/status :/Status		:/g' ipinfo.txt
sed -i 's/continent :/Continent	:/g' ipinfo.txt
sed -i 's/continentCode :/Continent Code	:/g' ipinfo.txt
sed -i 's/country :/Nama negara	:/g' ipinfo.txt
sed -i 's/countryCode :/Kode negara	:/g' ipinfo.txt
sed -i 's/region :/Wilayah		:/g' ipinfo.txt
sed -i 's/regionName :/Nama wilayah	:/g' ipinfo.txt
sed -i 's/city :/Kota		:/g' ipinfo.txt
sed -i 's/zip :/Kode pos	:/g' ipinfo.txt
sed -i 's/lat :/Garis lintang	:/g' ipinfo.txt
sed -i 's/lon :/Garis bujur	:/g' ipinfo.txt
sed -i 's/timezone :/Zona waktu	:/g' ipinfo.txt
sed -i 's/isp :/ISP		:/g' ipinfo.txt
sed -i 's/org :/Organisasi	:/g' ipinfo.txt
sed -i 's/as :/AS		:/g' ipinfo.txt
sed -i 's/asname :/AS Name		:/g' ipinfo.txt
sed -i 's/query :/Alamat ip	:/g' ipinfo.txt
echo " " >> ipinfo.txt
echo "===============================" >> ipinfo.txt
echo "=========   Zxvluks   ==========" >> ipinfo.txt
echo "===============================" >> ipinfo.txt
cat ipinfo.txt
rm ipinfo.txt
